[package]
name = "goalgetter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.27"
reqwest = "0.12.12"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
tokio = { version = "1.43.0", features = ["full"] }